# Tensorflow Fundamentals

In [185]:
import tensorflow as tf
import numpy as np 

In [31]:
print(tf.__version__)

2.18.0


In [82]:
tensor_1 = tf.constant([1,2,3],dtype = tf.int16)
tensor_2 = tf.constant([4,5,6])

In [83]:
matrix = tf.constant([[1,2,3],[1,3,5443]],dtype=tf.int16)

In [94]:
image_path = r'images\MainAfter.jpg'

# Wczytaj obraz jako tensor
image_raw = tf.io.read_file(image_path)
image_tensor = tf.image.decode_jpeg(image_raw)

# Konwersja typu danych obrazu
cat = tf.image.convert_image_dtype(image_tensor, dtype=tf.float32)

In [100]:
image_raw

<tf.Tensor: shape=(), dtype=string, numpy=b'\xff\xd8\xff\xdb\x00C\x00\x06\x04\x05\x06\x05\x04\x06\x06\x05\x06\x07\x07\x06\x08\n\x10\n\n\t\t\n\x14\x0e\x0f\x0c\x10\x17\x14\x18\x18\x17\x14\x16\x16\x1a\x1d%\x1f\x1a\x1b#\x1c\x16\x16 , #&\')*)\x19\x1f-0-(0%()(\xff\xdb\x00C\x01\x07\x07\x07\n\x08\n\x13\n\n\x13(\x1a\x16\x1a((((((((((((((((((((((((((((((((((((((((((((((((((\xff\xc2\x00\x11\x08\x02\xd0\x05\x00\x03\x01"\x00\x02\x11\x01\x03\x11\x01\xff\xc4\x00\x1b\x00\x00\x03\x01\x01\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x02\x03\x00\x04\x05\x06\x07\xff\xc4\x00\x1a\x01\x00\x03\x01\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x02\x03\x04\x05\x06\xff\xda\x00\x0c\x03\x01\x00\x02\x10\x03\x10\x00\x00\x01\xe5(\xde\x87\xd09Fi\xd9M\'db]\x94\xca|\x0e(+\xaf=&#\x0b$h\x1b\x01!\x00\x01\x00\x03\x142\x98l\x92\xab\x04 `\x858\xa30hE\xd5\xe6Y\xd5\xe21\xc5-\xb1f;4H,;j\x00!\xb5\x07U.9\xbcqk\x06\xccUe\xaaTt\xaa\x9aQ\x1d\xa2\xd1j\x936\xaaRu\x00\x90\xde\xc7\x00`\xcd3\xad.qms5\xa2\x8eA\xc2\xb5b

In [101]:
tf_var = tf.Variable(tensor_1)

In [ ]:
tf_var

<tf.Variable 'Variable:0' shape=(3,) dtype=int16, numpy=array([1, 2, 3], dtype=int16)>

In [110]:
tf_var[1],tensor_1[1]
# tensor_1[1] = 1


(<tf.Tensor: shape=(), dtype=int16, numpy=2>,
 <tf.Tensor: shape=(), dtype=int16, numpy=2>)

In [114]:
tf_var[1].assign(1)
# tf.Variable(cat)[0,0,0].assign(1)

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int16, numpy=array([1, 1, 3], dtype=int16)>

In [143]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(720,1800,3))
random_1

<tf.Tensor: shape=(720, 1800, 3), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646, -0.7535805 ],
        ...,
        [-2.4936357 , -0.28852805,  1.7299943 ],
        [-0.35014084,  0.73337597,  0.16695048],
        [ 1.447251  , -0.7769296 , -1.3409891 ]],

       [[-0.25242987,  0.18124843,  0.21652186],
        [-0.39056182,  0.5674989 , -1.7990805 ],
        [ 0.7416017 ,  0.08540826, -0.92541003],
        ...,
        [-0.7836007 , -0.06981037, -1.0268217 ],
        [ 0.08150938,  0.9299913 , -0.3388574 ],
        [-1.3251772 ,  0.78412384, -0.88901097]],

       [[ 0.48954362,  1.4758215 , -1.3093672 ],
        [ 0.6921207 ,  0.3832524 ,  2.609107  ],
        [-0.8816731 , -0.28114706,  1.1993747 ],
        ...,
        [-0.7835381 , -0.29012266, -0.48994786],
        [-0.5789103 ,  0.31020138, -0.13535425],
        [ 0.42908406,  0.01642662,  0.15302789]],

       ...,

    

In [147]:
x = 50
generator = tf.random.Generator.from_seed(x)
generator_1 = tf.random.Generator.from_seed(x)

first = generator.uniform(shape=(1,2,3))
last = generator_1.uniform(shape=(1,2,3))

In [148]:
first == last

<tf.Tensor: shape=(1, 2, 3), dtype=bool, numpy=
array([[[ True,  True,  True],
        [ True,  True,  True]]])>

In [153]:
var = tf.Variable([[[1,2,3],[123,500,1]]])

In [157]:
val = tf.constant(var)


In [176]:
val = tf.random.uniform(shape=(3,3,3))

In [216]:
tf.random.set_seed(42)
tf.random.shuffle(val) # shuffles tensors for better adjusting of CNN 

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[0.02479053, 0.2612611 , 0.82328546],
        [0.3767413 , 0.06203389, 0.6027752 ],
        [0.5250609 , 0.79265285, 0.69028723]],

       [[0.4027177 , 0.21640515, 0.6468617 ],
        [0.39856482, 0.9541826 , 0.859468  ],
        [0.61571085, 0.2849028 , 0.8270955 ]],

       [[0.83912694, 0.40730715, 0.81786335],
        [0.24965239, 0.60023713, 0.44314742],
        [0.15137315, 0.75109506, 0.5580486 ]]], dtype=float32)>

In [186]:
numpys = np.array([1,2,3])

In [187]:
tf.constant(numpys)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

In [221]:
tf.ones(shape=1),tf.zeros(shape=1),tf.eigvals(val)

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=complex64, numpy=
 array([[ 0.3785176 +0.j        ,  1.5301483 +0.j        ,
          0.08874724+0.j        ],
        [ 1.5048805 +0.j        , -0.36388463+0.12558515j,
         -0.36388463-0.12558515j],
        [-0.04974337+0.j        ,  1.7161422 +0.j        ,
          0.5175972 +0.j        ]], dtype=complex64)>)

In [226]:
x = tf.random.normal(shape=(2,24))
tf.reshape(x,shape=(2,4,-1))

<tf.Tensor: shape=(2, 4, 6), dtype=float32, numpy=
array([[[ 0.0307604 ,  0.29017973,  1.2829775 ,  0.81271535,
         -0.79449177,  0.20022836],
        [ 1.80325   , -1.0376493 , -1.234068  , -1.260827  ,
          0.11458235,  0.11852823],
        [-1.2859142 ,  1.2248926 ,  2.7304006 ,  0.5521646 ,
         -0.8338689 , -0.21482147],
        [ 0.05237458, -0.50573623, -0.715453  , -0.433889  ,
          1.0821081 , -0.08574483]],

       [[ 0.09840713, -0.3249235 , -0.72411925,  0.03978942,
          0.83454436,  0.16320741],
        [ 0.8429304 , -0.01803334, -0.41992235, -0.12656683,
         -0.6758276 , -0.49598095],
        [ 0.39346427, -0.13904887, -0.84857744,  1.0830246 ,
         -1.1008992 ,  0.09475911],
        [ 0.90238184, -1.2563496 , -1.0280035 , -0.25850686,
         -0.14330438, -1.3012673 ]]], dtype=float32)>